config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :books
  resources :users,only:[:index,:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length:{maximum: 200}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy

  validates :name, uniqueness: true, length:{ in: 2..20 }
  validates :introduction, length:{maximum: 50}


  has_one_attached :profile_image

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize:size).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end



  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    @books=Book.all
    @user=current_user
    if @book.save
    redirect_to book_path(@book.id),notice: "Processed successfully"
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @books =Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
  if @book.update(book_params)
    redirect_to book_path(@book.id),notice: "Processed successfully"
  else
    render :edit
  end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to'/books'
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
    @book=Book.new
  end

  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books
  end

  def edit
    @user = User.find(params[:id])
  if @user==current_user
    render :edit
  else
    redirect_to user_path(current_user)
  end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="Processed successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image("100x100") %>
  <table class="table">
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><p><%=user.name %></p></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><p><%= user.introduction %></p></th>
    </tr>
    </tbody>
  </table>

  <div class="btn btn-outline-secondary btn-block">
    <%= link_to edit_user_path(user.id),method: :get do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>


  <h2 class="mt-3">New book</h2>
  <%= form_with model:book,url:books_path do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <div>
  <%= f.submit"Create Book",class:"btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/books/_errors.html.erb
<% if book.errors.any? %>
<%= book.errors.count %>error occurred
<ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
      <%= render 'books/errors.html.erb',book: @book %>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>
            <%= form_with model: @book do |f| %>

            <h4>Title</h4>
            <%= f.text_field :title %>

            <h4>Opinion</h4>
            <%= f.text_area :body %>

            <div><%= f.submit 'Update Book',class:"btn btn-success" %></div>
            <div>
            <%=link_to "Show",book_path(@book.id) %>|<%= link_to"Back",books_path %>
            </div>
            <% end %>
          </div>
         </div>
        </div>

app/views/books/index.html.erb
  <p id="notice"></p>
    <div class="container px-5 px-sm-0">
      <div class="row">
      <%= render 'books/errors.html.erb',book: @book %>
      <%= render 'books/book.html.erb',book: @book,user: @user %>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                </tr>
              </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <%#= link_to image_tag(book.user.get_profile_image('80x80')), user_path(book.user.id) %>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image('80x80') %>
              <% end %>
            </td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
            </table>
        </div>
      </div>
    </diV>

app/views/books/show.html.erb
<p id="notice"></p>
    <div class="container px-5 px-sm-0">
    <div class="row">
        <%= render 'books/errors.html.erb',book: @book %>
        <%= render 'books/book.html.erb',book: @books,user: @user %>
        <div class="col-md-8 offset-md-1">
        <h2>Book detaill</h2>
    <table class="table">
  		  <tbody>
  		    <tr>
          <td><%= image_tag @user.get_profile_image("100x100") %><br>
          <%= link_to @user.name,user_path(@user.id) %>
          </td>
          <td><%= link_to @book.title,book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td> <% if @book.user==current_user %>
            <%=link_to "Edit",edit_book_path(@book.id) ,class:"btn btn-sm btn-success" %>
            <% end %>
          </td>
          <td><% if @book.user==current_user %>
          <%= link_to "Destroy",book_path(@book.id),method: :delete ,class:"btn btn-sm btn-danger " %>
            <% end %>
          </td>
          </tr>
        </tbody>
     </table>
    </div>
    </div>
    </div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 >Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
  <main>
    <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong></h1>
              <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
              <p>you can share and exchange  your opinions , inpressions , and emotions</p>
              <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <div class="btn btn-info btn-sm btn-block mb-3 sign_in">
            <%= link_to "Log in",new_user_session_path,method: :get %>
          </div>
            </div>
        <div class="row">
          <div class="btn btn-success btn-sm btn-block sign_up">
            <%= link_to "Sign up",new_user_registration_path,method: :get %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
      <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

         <div class="navbar-collapse collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
      <li>
       <%= link_to user_path(current_user.id),method: :get ,class:"nav-link text-light" do %>
       <i class="fas fa-home"></i>Home
       <% end %>
      </li>
      <li>
        <%= link_to users_path,method: :get ,class:"nav-link text-light" do %>
        <i class="fas fa-users"></i>Users
        <% end %>
      </li>
      <li>
        <%= link_to books_path,method: :get ,class:"nav-link text-light" do %>
        <i class="fas fa-book-open"></i>Books
        <% end %>
      </li>
      <li>
      <%= link_to destroy_user_session_path,method: :delete,class:"nav-link text-light" do %>
      <i class="fas fa-sign-out-alt"></i>Log out
      <% end %>
      </li>

      <% else %>
      <li>
        <%= link_to root_path,method: :get,class:"nav-link text-light" do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>
      <li>
        <%= link_to about_path,method: :get,class:"nav-link text-light" do %>
        <i class="fas fa-link"></i> About
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path,method: :get,class:"nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path,method: :get,class:"nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
        <% end %>
           </ul>
         </div>
       </div>
      </nav>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
      <% end %>

    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/_errors.html.erb
<% if user.errors.any? %>
<%= user.errors.count %>error prohibited this obj from being saved:
<ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <% if @user.errors.any? %>
            <%= @user.errors.count %>error occurred
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
              </ul>
            <% end %>

                <h2>User info</h2>

                <%= form_with model: @user do |f| %>


                <div><label for="inputName">Name</label></div>
                <div><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%></div>
                <div><label for="inputImage">Image</label></div>


                <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>

                <h4>Introduction</h4>
                <%= f.text_area :introduction %>

                <div><%= f.submit"Update User" , class:"btn btn-success" %></div>

                <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
    <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/errors.html.erb',book: @book %>
      <%= render 'books/book.html.erb',user: current_user ,book: @book%>
    <div class="col-md-8 offset-md-1">
<h2>users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <tbody>
<% @users.each do |user| %>
  <tr>
     <td><%= image_tag user.get_profile_image("80x80") %></td>
     <td><%= user.name %></td>
     <td><%= link_to "Show",user_path(user.id) %></td>
  </tr>
   <% end %>
  </tbody>
  </table>
  </div>
  </div>

app/views/users/show.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/errors.html.erb',book: @book %>
      <%= render 'books/book.html.erb',user: @user ,book: @book%>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
             <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(@user.id) do %>
                    <%= image_tag @user.get_profile_image("80x80") %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body%></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>